code --install-extension anthropic.claude-code
code --install-extension bmalehorn.vscode-fish
code --install-extension castwide.solargraph
code --install-extension charliermarsh.ruff
code --install-extension dbaeumer.vscode-eslint
code --install-extension detachhead.basedpyright
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension jdinhlife.gruvbox
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension misogi.ruby-rubocop
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode.makefile-tools
code --install-extension redhat.vscode-yaml
code --install-extension shakram02.bash-beautify
code --install-extension shopify.ruby-lsp
code --install-extension vira.vsc-vira-theme
code --install-extension whizkydee.material-palenight-theme
code --install-extension yzhang.markdown-all-in-one
